### ISSUE TITLE
Default the store name to the model file name when creating stores

### ISSUE THREAD

**Issue by aaguiarz** [openfga/cli#107]
When writing `fga store create --model mymodel.fga` default the `--name` parameter to the file name.

 `fga store create --model mymodel.fga` would be equivalent to  `fga store create --model mymodel.fga --name mymodel`

**Comment by parikxxit** [comment]
@aaguiarz I am start working on this issue

**Comment by rhamzeh** [comment]
Hey @parikxxit, thanks for your interest! Just so you don't waste time, this actually went in with [this PR](https://github.com/openfga/cli/pull/100)

However, if you'd like to contribute tests for this or code enhancements, please feel free :)
