### ISSUE TITLE
Provide an option in `tuple read` that outputs the format used in `tuple import`

### ISSUE THREAD

**Issue by aaguiarz** [openfga/cli#111]
The `tuple read` command displays tuples with this format

```{
      "key": {
        "object":"team:acme-marketing",
        "relation":"member",
        "user":"user:john"
      },
      "timestamp":"2023-07-28T23:06:50.555898Z"
    }
```
However, the `tuple import` command expects them in this format:
```
{
  "user": "user:anne",
  "relation": "can_view",
  "object": "document:roadmap"
}
```

We should have a way to output the format needed by `tuple read`.

It seems that the format used by `tuple import` is simpler to read, so it could make sense to use that one as the default for `tuple read`. However, given that is not the API's output, it will be more expensive to generate and will also be inconsistent with the output results. For that reason, it might be preferred to have a flag to output the simpler format.

I can't thing of a good flag name, some options:

--simple-json
--import-format

**Comment by rhamzeh** [comment]
Would adding documentation on how to do this by using `jq` work for a first step?
