### ISSUE TITLE
Add `-f` flag to allow FGA model files to be provided to the `fga model validate` command

### ISSUE THREAD

**Issue by jon-whit** [openfga/cli#187]
I'd like to be able to validate a model using the OpenFGA CLI, and my model is stored in a `model.fga` file.

```
# model.fga
model
  schema 1.1

type user

type document
  relations
    define viewer: [user]
```
and I'd like to be able to `fga model validate -f model.fga`.

**Comment by rhamzeh** [comment]
We don't support shorthand flags for the moment until the rest of the cli has stabilized.

You can do:
```sh
fga model validate --file model.fga
```

**Comment by jon-whit** [comment]
I was using an old version of the CLI. Nvm 😄
