### ISSUE TITLE
Standalone executable

### ISSUE THREAD

**Issue by dmatamoroscr** [openfga/cli#190]
Would it be possible to have a standalone executable that could be used to transform files between syntaxes? This would greatly benefit users from other languages.
I know writing a small script within our solution should be fairly simple, but an official standard way to do it would probably benefit the community as a whole.

**Comment by rhamzeh** [comment]
@dmatamoroscr - closing this issue as you can use the [FGA CLI](https://github.com/openfga/cli) to transform now. It's a standalone binary you can install.

Look for `fga model transform`
