### ISSUE TITLE
Test execution with example

### ISSUE THREAD

**Issue by FreEZer00** [openfga/cli#197]
Hey :) 
when executing the test from the readme I get the following exception: 

`fga model test --tests test.fga.yaml `

`goroutine 1 [running]:
github.com/openfga/openfga/pkg/storage/storagewrappers.NewBoundedConcurrencyTupleReader(...)
	/home/runner/go/pkg/mod/github.com/openfga/openfga@v1.3.6-0.20231103215350-a9f5e95a94da/pkg/storage/storagewrappers/boundedconcurrency.go:42
github.com/openfga/openfga/internal/graph.NewLocalChecker({0x8ce4398, 0xbb27c38}, {0xb8536b8, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/openfga/openfga@v1.3.6-0.20231103215350-a9f5e95a94da/internal/graph/check.go:176 +0xc9
github.com/openfga/openfga/pkg/server.(*Server).Check(0xb90bb80, {0x8ce38c4, 0x94638c0}, 0xbd1fa34)
	/home/runner/go/pkg/mod/github.com/openfga/openfga@v1.3.6-0.20231103215350-a9f5e95a94da/pkg/server/server.go:569 +0xa66
github.com/openfga/cli/internal/storetest.RunSingleLocalCheckTest(...)
	/home/runner/work/cli/cli/internal/storetest/localtest.go:17
github.com/openfga/cli/internal/storetest.RunLocalCheckTest(0xb90bb80, {{0xba03484, 0x9}, {0xba034a0, 0x8}, 0x0, 0xbf2a180}, {0xba01340, 0x2, 0x2}, ...)
	/home/runner/work/cli/cli/internal/storetest/localtest.go:52 +0x2af
github.com/openfga/cli/internal/storetest.RunLocalTest(0xb90bb80, {{0xba033f0, 0x6}, {0xba66f00, 0x1c}, {0xbf2a100, 0x1, 0x1}, {0xb921248, 0x1, ...}, ...}, ...)
	/home/runner/work/cli/cli/internal/storetest/localtest.go:165 +0x1ad
github.com/openfga/cli/internal/storetest.RunTest(0xb8c5a70, 0xb90bb80, {{0xba033f0, 0x6}, {0xba66f00, 0x1c}, {0xbf2a100, 0x1, 0x1}, {0xb921248, ...}, ...}, ...)
	/home/runner/work/cli/cli/internal/storetest/tests.go:28 +0x1e8
github.com/openfga/cli/internal/storetest.RunTests(0xb8c5a70, {{0xba03310, 0xa}, {0x0, 0x0}, {0xba03330, 0xb}, {0xbf2a020, 0x1, 0x1}, ...}, ...)
	/home/runner/work/cli/cli/internal/storetest/tests.go:44 +0x1c0
github.com/openfga/cli/cmd/model.glob..func3(0x94473c0, {0xb810780, 0x0, 0x2})
	/home/runner/work/cli/cli/cmd/model/test.go:68 +0x5e2
github.com/spf13/cobra.(*Command).execute(0x94473c0, {0xb810770, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x880
github.com/spf13/cobra.(*Command).ExecuteC(0x9446ac0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/openfga/cli/cmd.Execute()
	/home/runner/work/cli/cli/cmd/root.go:47 +0x23
main.main()
	/home/runner/work/cli/cli/main.go:21 +0x17`

Am I doing anything wrong or is there a bug? 
Using ubuntu and installed the debian package in version 0.2.0

Thank you!

**Comment by rhamzeh** [comment]
Hey @FreEZer00, thanks for raising the issue.

If your `tests.fga.yaml` file does not contain any private data, can you share it here?

Otherwise, do you think you would be OK with sharing it privately?

**Comment by FreEZer00** [comment]
Hi @rhamzeh 
I literally just copied the stuff from the readme. No changes at all

**Comment by aaguiarz** [comment]
@rhamzeh @FreEZer00 

I just tried from MacOS and I did not get any error, we might need to test in Ubuntu

**Comment by FreEZer00** [comment]
Thanks to both of you! 
I will try different machine as well.

**Comment by rhamzeh** [comment]
On both Fedora and Ubuntu, `fga@v0.2.0` should throw an error saying that the file was not found if you don't have a file locally

![Screenshot from 2023-12-05 16-44-44](https://github.com/openfga/cli/assets/536147/2ac47897-d198-4877-90b2-d4fe160dd151)
![Screenshot from 2023-12-05 16-44-12](https://github.com/openfga/cli/assets/536147/94a0e1d4-5e9e-4a16-bec2-95891cebd207)

**Comment by rhamzeh** [comment]
@FreEZer00 - you mentioned you installed the debian version of v0.2.0, can you confirm which one?

In general if you have a 64-bit intel/amd machine, you would need: [fga_0.2.0_linux_amd64.deb](https://github.com/openfga/cli/releases/download/v0.2.0/fga_0.2.0_linux_amd64.deb)

Please make sure you are not installing the arm64 or the 386 or the termux versions unless they match your machine architecture.

Can you also share the result when your run: `fga version`?

**Comment by FreEZer00** [comment]
I just reinstalled it works now. Probably had a wrong version installed. 

Thank you so much, sorry for the trouble :)
