### ISSUE TITLE
Create Github Actions for Model Validation/Deployment

### ISSUE THREAD

**Issue by aaguiarz** [openfga/cli#202]
- Create a github action that runs a command like:

```fga model test --tests store.fga.yaml```

This will help OpenFGA users run the tests as part of their CI/CD Pipelines, e.g.

https://github.com/openfga/sample-stores/blob/main/.github/workflows/main.yaml#L40

- Create a github action that deploys a model to an OpenFGA store and gets the model id.

**Comment by rhamzeh** [comment]
Closed by:
- https://github.com/marketplace/actions/openfga-model-testing-action
- https://github.com/marketplace/actions/openfga-model-deploy-action
