### ISSUE TITLE
Configure distinct user agent

### ISSUE THREAD

**Issue by jpadilla** [openfga/cli#22]
Instead of using the default `User-Agent` set by the SDK, configure a distinct one for cli.

**Comment by rhamzeh** [comment]
Open question: What should the User Agent be?

SDKs are of the format: `openfga-sdk {sdkId}/{packageVersion}`, e.g. `openfga-sdk go/0.1.1`

Suggestion for the CLI would be: `openfga-cli/{packageVersion}` e.g. `openfga-cli/0.0.1`

**Comment by jpadilla** [comment]
> Open question: What should the User Agent be?
> 
> SDKs are of the format: `openfga-sdk {sdkId}/{packageVersion}`, e.g. `openfga-sdk go/0.1.1`
> 
> Suggestion for the CLI would be: `openfga-cli/{packageVersion}` e.g. `openfga-cli/0.0.1`

your suggestion tracks 👍
