### ISSUE TITLE
Support OAuth Scope parameter for client authentication

### ISSUE THREAD

**Issue by nverbos-godaddy** [openfga/cli#231]
Currently the cli supports passing `client-id` and `client-secret` as parameters for getting an OAuth access token from an OAuth Authorization server.  However some OAuth authorization servers may not issue a token with the necessary scope unless a `scope` param is passed on the token request. 

We should add support for a new cli flag, config value, and environment variable for specifying the scope of the access token requested from the authorization server.

**Comment by le-yams** [comment]
Hey @nverbos-godaddy ,

I was about to open an issue about OAuth2 support but just saw yours so I'm referencing it for my PR #232 😃.
It's still a draft as it needs an update of the go-sdk (see [my comment here](https://github.com/openfga/cli/pull/232#issuecomment-1898124768)).
