### ISSUE TITLE
Simplify error messages on `tuple write`

### ISSUE THREAD

**Issue by aaguiarz** [openfga/cli#255]
When you call `tuple write` and there's an error when writing/deleting a tuple, the CLI returns a `failed` array with one entry for each failed tuple and a `reason` field.

The`reason` field has content similar to:

```
"reason":"Write validation error for POST Write with body {\"code\":\"write_failed_due_to_invalid_input\",\"message\":\"cannot write a tuple which already exists: user: 'user:anne', relation: 'member', object: 'organization:acme': invalid write input\"}\n with error code write_failed_due_to_invalid_input error message: cannot write a tuple which already exists: user: 'user:anne', relation: 'member', object: 'organization:acme': invalid write input"
```

The message is repetitive. In this case, it would be easier to read if it just had the error returned by the server:
```
"reason":"error message: cannot write a tuple which already exists: user: 'user:anne', relation: 'member', object: 'organization:acme': invalid write input"
```

**Comment by aaguiarz** [comment]
@shruti2522 sure, thanks a lot for your help!

**Comment by shruti2522** [comment]
Thanks @aaguiarz. 

When attempting to import a file, I received the following error message:
```
shruti@fedora:~/cncf/cli$ ./dist/fga store import --file example/store_abac.fga.yaml
Error: failed to create store FolderBox due to Post "http://localhost:8080/stores": dial tcp [::1]:8080: connect: connection refused
```
Do I need to configure environment variables, considering that `localhost:8080` is default?"

**Comment by ewanharris** [comment]
@shruti2522, if you have an existing OpenFGA instance you want to run against you can check the docs for configuring the CLI to point to that [here](https://openfga.dev/docs/getting-started/cli).

For testing I'd recommend either using a [docker container](https://openfga.dev/docs/getting-started/setup-openfga/docker) that way the OpenFGA instance can be discarded after testing.
