### ISSUE TITLE
`store import` without tuples always fails

### ISSUE THREAD

**Issue by Pie4kaiz** [openfga/cli#368]
When using `store import` just for the model but without or with an empty `tuples` section, it always errors with:
`Error: failed to import store: failed to finish progress bar: max must be greater than 0`

From looking at the code, the model should've still been imported though, so just a surface thing.

**Comment by ap0calypse8** [comment]
Hey I have forked the repo and already made changes to the code . help me out with the testing, how do i run the tests after building?

**Comment by ap0calypse8** [comment]
please review my pr #408
