### ISSUE TITLE
Concurent Map Write Error

### ISSUE THREAD

**Issue by felix-ulonska** [openfga/cli#413]
In Telemetry it seems to trigger a concurrent map error:

```
Code: 2

Stderr:
fatal error: concurrent map writes

goroutine 21 [running]:
github.com/openfga/go-sdk/internal/telemetry.(*Metrics).GetHistogram
```

**Comment by aaguiarz** [comment]
@felix-ulonska Are you seeing the problem on the CLI or in the GO SDK? 

Are you trying with the latest version of the GO SDK? We addressed a similar issue https://github.com/openfga/go-sdk/releases/tag/v0.6.3

**Comment by rhamzeh** [comment]
We haven't bumped the Go SDK in the CLI yet, so that would be the cause. 

https://github.com/openfga/cli/blob/main/go.mod#L14

Thanks @felix-ulonska for filing this!

**Comment by felix-ulonska** [comment]
> [@felix-ulonska](https://github.com/felix-ulonska) Are you seeing the problem on the CLI or in the GO SDK?
> 
> Are you trying with the latest version of the GO SDK? We addressed a similar issue https://github.com/openfga/go-sdk/releases/tag/v0.6.3

When I run the "fga" cli. I do directly use the go openfga sdk

**Comment by rhamzeh** [comment]
Thanks @felix-ulonska - this should be fixed in our next release.

You can pull down the main branch and use that, or wait till the release is out. It's likely going to be out within the next few days
