### ISSUE TITLE
Self-signed Certificate Issue with Docker Container

### ISSUE THREAD

**Issue by Valkryst** [openfga/cli#427]
I have a Docker Compose environment with `openfga/openfga:latest` and `openfga/cli:latest` containers, and I'm also using temporarily generated, self-signed certificates for development purposes.

When running the CLI container, using a basic `docker compose run openfga-cli store list` it outputs the following error:

```
Error: failed to list stores due to Get "https://openfga:8080/stores?continuation_token=": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Is there a recommended way to force the CLI to accept/use my self-signed certificate?

**Comment by rhamzeh** [comment]
Hey @Valkryst - in general I would say you would have to follow the same steps to get the certificate loaded into the docker.

This answer on StackOverflow walks you through that: https://stackoverflow.com/a/54403068

**Comment by Valkryst** [comment]
It seems as though the `openfga/cli` container doesn't allow for commands to be run VIA bash. I got it working with this `Dockerfile`:

```shell
FROM debian:stable-slim

RUN apt-get update && apt-get install -y ca-certificates wget

RUN wget https://github.com/openfga/cli/releases/download/v0.6.2/fga_0.6.2_linux_amd64.deb -O /tmp/fga.deb \
    && apt install -y /tmp/fga.deb \
    && rm /tmp/fga.deb

# We do "&& tail -f /dev/null" to keep the container running, so that we can exec into it to run CLI commands.
CMD ["bash", "-c", "update-ca-certificates && tail -f /dev/null"]
```
